# Generated by Django 5.2.1 on 2025-05-18 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History_Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='History_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=20)),
                ('prediction', models.CharField(max_length=20)),
                ('probability', models.FloatField()),
                ('Prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_records', to='history.history_prediction')),
            ],
            options={
                'verbose_name_plural': 'Histories',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Prediction_Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=20)),
                ('probability', models.FloatField(default=0)),
                ('prediction_History', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='history.history_prediction')),
            ],
            options={
                'ordering': ['-probability'],
            },
        ),
    ]
